name: "ts-dev-container"

volumes:
  workspace-data:
  ssh-data:
  root-cache:


networks:
  dev-container-net:


services:
  app:
    container_name: app
    image: ts-dev-container-app
    build: { dockerfile: dev.dockerfile }
    volumes:
      - workspace-data:/workspace
      - ssh-data:/root/.ssh
      - root-cache:/root/.cache
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "/usr/sbin/sshd -D && while sleep 1000; do :; done"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "2222:22"
    networks:
      - dev-container-net
