name: "dev-container"

volumes:
  workspace-data:
  ssh-data:
  root-cache:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./cache

networks:
  dev-container-net:


services:
  dev-container:
    container_name: dev-container
    image: dev-container
    build: { dockerfile: ./dockerfiles/ubuntu.dockerfile }
    volumes:
      - workspace-data:/workspace
      - ssh-data:/root/.ssh
      - root-cache:/root/.cache
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "/usr/sbin/sshd -D && sleep infinity"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9022:22"
    networks:
      - dev-container-net
