name: "dev-container"

volumes:
  db-data:


networks:
  dev-container-net:


services:
  dev-mongo-db:
    container_name: dev-mongo-db
    image: mongo
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: mongo-pass
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-container-net
