name: "dev-container"

networks:
  dev-container-net:


services:
  dev-redis:
    container_name: dev-redis
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-container-net
